Update LLM attr tutorial notebook with note on required Captum version (#1496)
Summary:

Got https://github.com/pytorch/captum/issues/1486 when I was oncall a while ago. A user ran into this error:
> TypeError: ShapleyValues.attribute() got an unexpected keyword argument 'skip_tokens'

due to being on a package of Captum where
> LLMAttribution.attribute() doesn't have skip_tokens as a parameter, and therefore it's being passed to ShapleyValues.attribute() as part of **kwarg, though ShapleyValues never supported skip_tokens

It's not sufficient to be on the latest Captum release (v0.7), atp they need to install from Github

Differential Revision: D69566114