Address likely package mismatch issues (#1634)
Summary:

Previous CI runs were encountering issues:

1. https://github.com/.../runs/16867033035/job/47776474001

```
E           torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device
E           CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
E           For debugging consider passing CUDA_LAUNCH_BLOCKING=1
E           Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

  - likely because cuda 12.1 was no longer supported by newest versions of pytorch installed
  - note, 12.9 also failed with `nvidia-container-cli: requirement error: unsatisfied condition: cuda>=12.9, please update your driver to a newer version, or use an earlier cuda container: unknown.`

2. https://github.com/pytorch/captum/actions/runs/16867033037/job/47775775171

`tests/attr/test_llm_attr_hf_compatibility.py:76: error: Argument 1 to "__call__" of "_Wrapped" has incompatible type "str"; expected "PreTrainedModel" [arg-type]`

This is likely due to (1) mismatched pytorch versions vs the cuda version 12.1 specified in test-pip-gpu.yml, triggered by [new PyTorch release](https://github.com/pytorch/pytorch/releases) and (2) lack of full typing causing error thrown by `mypy`, triggered by loosely defined `mypy>=0.760` probably pulling [new MyPy release](https://pypi.org/project/mypy/#history)

Differential Revision: D80120024