Add support for captum toplevel-import. (#912)
Summary:
This fixes issue https://github.com/pytorch/captum/issues/680 Strange import issue --> AttributeError: module 'captum' has no attribute 'attr'

In most python packages, you can import the toplevel package, like numpy, scipy, torch, etc.. and then access the submodules simply by the dot-operator. Like you can use `import numpy` and after that you can use any submodules à la `numpy.random.uniform`.

With this PR, you can just `import captum` and then for example use `captum.attr.DeepLift` or `captum.robust.Perturbation` instead of having to import both. It's just a small convenience, and I think there are more people that expect this kind of import to work but don't bother to create an issue out of this.

I hope this PR is considered as helpful.

Pull Request resolved: https://github.com/pytorch/captum/pull/912

Reviewed By: NarineK

Differential Revision: D37053826

Pulled By: vivekmig

fbshipit-source-id: 64fa2be7651ca30571d1eb85b45dd11410676c4b